import { createHash } from "node:crypto";

export type CarTier = "Budget" | "Mid-Range" | "Exotic" | "Hypercar" | "Ultra-Rare";

export interface Car {
  id: string;
  name: string;
  price: number;
  tier: CarTier;
  image: string;
  wikiTitle: string;
  hp: number;
  topSpeed: number;
  origin: string;
  googleQuery: string;
  color: number;
}

function wikiFile(filename: string, width = 800): string {
  const name = filename.replace(/ /g, "_");
  const hash = createHash("md5").update(name).digest("hex");
  const a = hash[0];
  const ab = hash.slice(0, 2);
  const enc = encodeURIComponent(name);
  return `https://upload.wikimedia.org/wikipedia/commons/thumb/${a}/${ab}/${enc}/${width}px-${enc}`;
}

export const TIER_EMOJI: Record<CarTier, string> = {
  "Budget":     "🟢",
  "Mid-Range":  "🔵",
  "Exotic":     "🟣",
  "Hypercar":   "🟠",
  "Ultra-Rare": "🔴",
};

export const TIER_COLOR: Record<CarTier, number> = {
  "Budget":     0x2ecc71,
  "Mid-Range":  0x3498db,
  "Exotic":     0x9b59b6,
  "Hypercar":   0xe67e22,
  "Ultra-Rare": 0xe74c3c,
};

export const CARS_PER_PAGE = 5;
export const SELL_RATIO = 0.6;

export const CARS: Car[] = [
  // ──────────────── BUDGET ────────────────────────────────────────────────────
  {
    id: "honda-civic-type-r",
    name: "Honda Civic Type R",
    price: 28_000,
    tier: "Budget",
    image: wikiFile("2017_Honda_Civic_Type_R_(FK8)_(cropped).jpg"),
    wikiTitle: "Honda_Civic_Type_R",
    hp: 315, topSpeed: 169, origin: "Japan 🇯🇵",
    googleQuery: "Honda Civic Type R FK8",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "toyota-gr-supra",
    name: "Toyota GR Supra",
    price: 55_000,
    tier: "Budget",
    image: wikiFile("Toyota_GR_Supra_(A90)_(cropped).jpg"),
    wikiTitle: "Toyota_GR_Supra",
    hp: 382, topSpeed: 155, origin: "Japan 🇯🇵",
    googleQuery: "Toyota GR Supra A90 2020",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "ford-mustang-gt500",
    name: "Ford Mustang Shelby GT500",
    price: 80_000,
    tier: "Budget",
    image: wikiFile("2020_Ford_Mustang_Shelby_GT500,_front_11.6.19.jpg"),
    wikiTitle: "Shelby_Mustang",
    hp: 760, topSpeed: 180, origin: "USA 🇺🇸",
    googleQuery: "Ford Mustang Shelby GT500 2020",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "bmw-m3-competition",
    name: "BMW M3 Competition",
    price: 75_000,
    tier: "Budget",
    image: wikiFile("BMW_M3_competition_(G80)_blue.jpg"),
    wikiTitle: "BMW_M3",
    hp: 503, topSpeed: 180, origin: "Germany 🇩🇪",
    googleQuery: "BMW M3 Competition G80 2021",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "porsche-cayman-gt4",
    name: "Porsche 718 Cayman GT4",
    price: 85_000,
    tier: "Budget",
    image: wikiFile("Porsche_718_Cayman_GT4_(982C)_(cropped).jpg"),
    wikiTitle: "Porsche_718",
    hp: 414, topSpeed: 188, origin: "Germany 🇩🇪",
    googleQuery: "Porsche 718 Cayman GT4 2022",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "dodge-challenger-hellcat",
    name: "Dodge Challenger SRT Hellcat",
    price: 62_000,
    tier: "Budget",
    image: wikiFile("2015_Dodge_Challenger_SRT_Hellcat_in_White,_front_4.23.19.jpg"),
    wikiTitle: "Dodge_Challenger",
    hp: 717, topSpeed: 199, origin: "USA 🇺🇸",
    googleQuery: "Dodge Challenger SRT Hellcat",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "chevrolet-camaro-zl1",
    name: "Chevrolet Camaro ZL1",
    price: 70_000,
    tier: "Budget",
    image: wikiFile("2017_Chevrolet_Camaro_ZL1,_front_8.31.18.jpg"),
    wikiTitle: "Chevrolet_Camaro",
    hp: 650, topSpeed: 198, origin: "USA 🇺🇸",
    googleQuery: "Chevrolet Camaro ZL1 2017",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "subaru-wrx-sti",
    name: "Subaru WRX STI",
    price: 40_000,
    tier: "Budget",
    image: wikiFile("2018_Subaru_WRX_STI_(US),_front_7.21.19.jpg"),
    wikiTitle: "Subaru_WRX",
    hp: 310, topSpeed: 158, origin: "Japan 🇯🇵",
    googleQuery: "Subaru WRX STI 2018",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "mitsubishi-lancer-evo-x",
    name: "Mitsubishi Lancer Evolution X",
    price: 35_000,
    tier: "Budget",
    image: wikiFile("Mitsubishi_Lancer_Evolution_X_GSR.jpg"),
    wikiTitle: "Mitsubishi_Lancer_Evolution",
    hp: 291, topSpeed: 152, origin: "Japan 🇯🇵",
    googleQuery: "Mitsubishi Lancer Evolution X",
    color: TIER_COLOR["Budget"],
  },
  {
    id: "nissan-skyline-gtr-r34",
    name: "Nissan Skyline GT-R R34",
    price: 90_000,
    tier: "Budget",
    image: wikiFile("Nissan_Skyline_R34_GTR_Nurburgring.jpg"),
    wikiTitle: "Nissan_Skyline_GT-R",
    hp: 320, topSpeed: 155, origin: "Japan 🇯🇵",
    googleQuery: "Nissan Skyline GT-R R34",
    color: TIER_COLOR["Budget"],
  },
  // ──────────────── MID-RANGE ─────────────────────────────────────────────────
  {
    id: "bmw-m4-competition",
    name: "BMW M4 Competition",
    price: 90_000,
    tier: "Mid-Range",
    image: wikiFile("BMW_M4_Competition_(G82)_IMG_3281.jpg"),
    wikiTitle: "BMW_M4",
    hp: 503, topSpeed: 180, origin: "Germany 🇩🇪",
    googleQuery: "BMW M4 Competition G82",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "nissan-gtr-nismo",
    name: "Nissan GT-R Nismo",
    price: 215_000,
    tier: "Mid-Range",
    image: wikiFile("2017_Nissan_GT-R_NISMO,_front_4.22.18.jpg"),
    wikiTitle: "Nissan_GT-R",
    hp: 600, topSpeed: 196, origin: "Japan 🇯🇵",
    googleQuery: "Nissan GT-R R35 Nismo",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "porsche-911-gt3-rs",
    name: "Porsche 911 GT3 RS",
    price: 225_000,
    tier: "Mid-Range",
    image: wikiFile("Porsche_911_GT3_RS_992_2022_–_f_18062023.jpg"),
    wikiTitle: "Porsche_911_GT3",
    hp: 518, topSpeed: 184, origin: "Germany 🇩🇪",
    googleQuery: "Porsche 911 GT3 RS 992",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "ferrari-roma",
    name: "Ferrari Roma",
    price: 280_000,
    tier: "Mid-Range",
    image: wikiFile("Ferrari_Roma_(cropped).jpg"),
    wikiTitle: "Ferrari_Roma",
    hp: 611, topSpeed: 198, origin: "Italy 🇮🇹",
    googleQuery: "Ferrari Roma 2020",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "lamborghini-urus",
    name: "Lamborghini Urus",
    price: 210_000,
    tier: "Mid-Range",
    image: wikiFile("Lamborghini_Urus_-_2019_Geneva_Motor_Show.jpg"),
    wikiTitle: "Lamborghini_Urus",
    hp: 641, topSpeed: 190, origin: "Italy 🇮🇹",
    googleQuery: "Lamborghini Urus SUV",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "mclaren-gt",
    name: "McLaren GT",
    price: 210_000,
    tier: "Mid-Range",
    image: wikiFile("McLaren_GT_at_Goodwood_2019.jpg"),
    wikiTitle: "McLaren_GT",
    hp: 612, topSpeed: 203, origin: "UK 🇬🇧",
    googleQuery: "McLaren GT 2020",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "aston-martin-db11",
    name: "Aston Martin DB11",
    price: 195_000,
    tier: "Mid-Range",
    image: wikiFile("Aston_Martin_DB11_(2016_Geneva_Motor_Show).jpg"),
    wikiTitle: "Aston_Martin_DB11",
    hp: 503, topSpeed: 187, origin: "UK 🇬🇧",
    googleQuery: "Aston Martin DB11 V12",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "bentley-continental-gt",
    name: "Bentley Continental GT",
    price: 220_000,
    tier: "Mid-Range",
    image: wikiFile("Bentley_Continental_GT_III_(2018).jpg"),
    wikiTitle: "Bentley_Continental_GT",
    hp: 650, topSpeed: 207, origin: "UK 🇬🇧",
    googleQuery: "Bentley Continental GT 2020",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "mercedes-amg-gt-black-series",
    name: "Mercedes-AMG GT Black Series",
    price: 330_000,
    tier: "Mid-Range",
    image: wikiFile("Mercedes-AMG_GT_Black_Series_(C190)_front_MHV.jpg"),
    wikiTitle: "Mercedes-AMG_GT",
    hp: 720, topSpeed: 202, origin: "Germany 🇩🇪",
    googleQuery: "Mercedes AMG GT Black Series",
    color: TIER_COLOR["Mid-Range"],
  },
  {
    id: "porsche-taycan-turbo-s",
    name: "Porsche Taycan Turbo S",
    price: 185_000,
    tier: "Mid-Range",
    image: wikiFile("Porsche_Taycan_Turbo_S_IMG_0614.jpg"),
    wikiTitle: "Porsche_Taycan",
    hp: 750, topSpeed: 161, origin: "Germany 🇩🇪",
    googleQuery: "Porsche Taycan Turbo S electric",
    color: TIER_COLOR["Mid-Range"],
  },
  // ──────────────── EXOTIC ────────────────────────────────────────────────────
  {
    id: "lamborghini-huracan-evo",
    name: "Lamborghini Huracán EVO",
    price: 265_000,
    tier: "Exotic",
    image: wikiFile("Lamborghini_Huracán_EVO_Spyder_(2019)_(cropped).jpg"),
    wikiTitle: "Lamborghini_Huracán",
    hp: 631, topSpeed: 202, origin: "Italy 🇮🇹",
    googleQuery: "Lamborghini Huracan EVO",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "mclaren-720s",
    name: "McLaren 720S",
    price: 315_000,
    tier: "Exotic",
    image: wikiFile("McLaren_720S_(39395654025).jpg"),
    wikiTitle: "McLaren_720S",
    hp: 710, topSpeed: 212, origin: "UK 🇬🇧",
    googleQuery: "McLaren 720S",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "ferrari-sf90-stradale",
    name: "Ferrari SF90 Stradale",
    price: 625_000,
    tier: "Exotic",
    image: wikiFile("Ferrari_SF90_Stradale_(cropped).jpg"),
    wikiTitle: "Ferrari_SF90_Stradale",
    hp: 986, topSpeed: 211, origin: "Italy 🇮🇹",
    googleQuery: "Ferrari SF90 Stradale",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "bugatti-veyron",
    name: "Bugatti Veyron 16.4",
    price: 1_700_000,
    tier: "Exotic",
    image: wikiFile("Bugatti_Veyron_16.4_(silver-black),_front_8.27.10.jpg"),
    wikiTitle: "Bugatti_Veyron",
    hp: 1001, topSpeed: 253, origin: "France 🇫🇷",
    googleQuery: "Bugatti Veyron 16.4 Super Sport",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "ferrari-laferrari",
    name: "Ferrari LaFerrari",
    price: 1_420_000,
    tier: "Exotic",
    image: wikiFile("LaFerrari_(2013_Geneva_Motor_Show).jpg"),
    wikiTitle: "LaFerrari",
    hp: 949, topSpeed: 217, origin: "Italy 🇮🇹",
    googleQuery: "Ferrari LaFerrari hybrid",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "porsche-918-spyder",
    name: "Porsche 918 Spyder",
    price: 845_000,
    tier: "Exotic",
    image: wikiFile("Porsche_918_Spyder_(cropped).jpg"),
    wikiTitle: "Porsche_918_Spyder",
    hp: 887, topSpeed: 214, origin: "Germany 🇩🇪",
    googleQuery: "Porsche 918 Spyder hybrid",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "mclaren-p1",
    name: "McLaren P1",
    price: 1_150_000,
    tier: "Exotic",
    image: wikiFile("McLaren_P1_(2013_Paris_Motor_Show).jpg"),
    wikiTitle: "McLaren_P1",
    hp: 903, topSpeed: 217, origin: "UK 🇬🇧",
    googleQuery: "McLaren P1 hybrid hypercar",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "lamborghini-aventador-svj",
    name: "Lamborghini Aventador SVJ",
    price: 518_000,
    tier: "Exotic",
    image: wikiFile("Lamborghini_Aventador_SVJ_(34975392453).jpg"),
    wikiTitle: "Lamborghini_Aventador",
    hp: 759, topSpeed: 217, origin: "Italy 🇮🇹",
    googleQuery: "Lamborghini Aventador SVJ",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "aston-martin-one-77",
    name: "Aston Martin One-77",
    price: 1_850_000,
    tier: "Exotic",
    image: wikiFile("Aston_Martin_One-77_(2011_DC_Auto_Show).jpg"),
    wikiTitle: "Aston_Martin_One-77",
    hp: 750, topSpeed: 220, origin: "UK 🇬🇧",
    googleQuery: "Aston Martin One-77",
    color: TIER_COLOR["Exotic"],
  },
  {
    id: "pagani-zonda-f",
    name: "Pagani Zonda F",
    price: 1_000_000,
    tier: "Exotic",
    image: wikiFile("Pagani_Zonda_F_-_2005_Geneva_Motor_Show.jpg"),
    wikiTitle: "Pagani_Zonda",
    hp: 602, topSpeed: 214, origin: "Italy 🇮🇹",
    googleQuery: "Pagani Zonda F",
    color: TIER_COLOR["Exotic"],
  },
  // ──────────────── HYPERCAR ──────────────────────────────────────────────────
  {
    id: "rimac-nevera",
    name: "Rimac Nevera",
    price: 2_400_000,
    tier: "Hypercar",
    image: wikiFile("Rimac_Nevera_(cropped).jpg"),
    wikiTitle: "Rimac_Nevera",
    hp: 1914, topSpeed: 258, origin: "Croatia 🇭🇷",
    googleQuery: "Rimac Nevera electric hypercar",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "koenigsegg-agera-rs",
    name: "Koenigsegg Agera RS",
    price: 2_100_000,
    tier: "Hypercar",
    image: wikiFile("Koenigsegg_Agera_RS_at_Monterey_Car_Week_2016_(cropped).jpg"),
    wikiTitle: "Koenigsegg_Agera",
    hp: 1360, topSpeed: 278, origin: "Sweden 🇸🇪",
    googleQuery: "Koenigsegg Agera RS",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "pagani-huayra-roadster-bc",
    name: "Pagani Huayra Roadster BC",
    price: 3_400_000,
    tier: "Hypercar",
    image: wikiFile("Pagani_Huayra_Roadster_BC_-_Geneva_Motor_Show_2019.jpg"),
    wikiTitle: "Pagani_Huayra",
    hp: 791, topSpeed: 238, origin: "Italy 🇮🇹",
    googleQuery: "Pagani Huayra Roadster BC",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "koenigsegg-jesko-absolut",
    name: "Koenigsegg Jesko Absolut",
    price: 3_000_000,
    tier: "Hypercar",
    image: wikiFile("Koenigsegg_Jesko_Absolut_-_Geneva_International_Motor_Show_2020.jpg"),
    wikiTitle: "Koenigsegg_Jesko",
    hp: 1600, topSpeed: 330, origin: "Sweden 🇸🇪",
    googleQuery: "Koenigsegg Jesko Absolut",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "bugatti-chiron-super-sport",
    name: "Bugatti Chiron Super Sport",
    price: 3_900_000,
    tier: "Hypercar",
    image: wikiFile("Bugatti_Chiron_Super_Sport_300+_(cropped).jpg"),
    wikiTitle: "Bugatti_Chiron",
    hp: 1577, topSpeed: 304, origin: "France 🇫🇷",
    googleQuery: "Bugatti Chiron Super Sport 300+",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "mclaren-speedtail",
    name: "McLaren Speedtail",
    price: 2_250_000,
    tier: "Hypercar",
    image: wikiFile("McLaren_Speedtail_-_Goodwood_Festival_of_Speed_2019_(cropped).jpg"),
    wikiTitle: "McLaren_Speedtail",
    hp: 1035, topSpeed: 250, origin: "UK 🇬🇧",
    googleQuery: "McLaren Speedtail hyper-GT",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "aston-martin-valkyrie",
    name: "Aston Martin Valkyrie",
    price: 3_200_000,
    tier: "Hypercar",
    image: wikiFile("Aston_Martin_Valkyrie_(2021_Goodwood_Festival_of_Speed)_(cropped).jpg"),
    wikiTitle: "Aston_Martin_Valkyrie",
    hp: 1139, topSpeed: 250, origin: "UK 🇬🇧",
    googleQuery: "Aston Martin Valkyrie hypercar",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "ferrari-fxx-k",
    name: "Ferrari FXX K",
    price: 2_800_000,
    tier: "Hypercar",
    image: wikiFile("Ferrari_FXX_K_Evo_(cropped).jpg"),
    wikiTitle: "LaFerrari",
    hp: 1050, topSpeed: 217, origin: "Italy 🇮🇹",
    googleQuery: "Ferrari FXX K Evo track car",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "bugatti-divo",
    name: "Bugatti Divo",
    price: 5_800_000,
    tier: "Hypercar",
    image: wikiFile("Bugatti_Divo_IAA_2019_(cropped).jpg"),
    wikiTitle: "Bugatti_Divo",
    hp: 1479, topSpeed: 236, origin: "France 🇫🇷",
    googleQuery: "Bugatti Divo hypercar",
    color: TIER_COLOR["Hypercar"],
  },
  {
    id: "koenigsegg-one-1",
    name: "Koenigsegg One:1",
    price: 2_850_000,
    tier: "Hypercar",
    image: wikiFile("Koenigsegg_One1_(cropped).jpg"),
    wikiTitle: "Koenigsegg_Agera",
    hp: 1341, topSpeed: 273, origin: "Sweden 🇸🇪",
    googleQuery: "Koenigsegg One:1 megacar",
    color: TIER_COLOR["Hypercar"],
  },
  // ──────────────── ULTRA-RARE ────────────────────────────────────────────────
  {
    id: "lamborghini-veneno",
    name: "Lamborghini Veneno",
    price: 4_500_000,
    tier: "Ultra-Rare",
    image: wikiFile("Lamborghini_Veneno_(cropped).jpg"),
    wikiTitle: "Lamborghini_Veneno",
    hp: 750, topSpeed: 221, origin: "Italy 🇮🇹",
    googleQuery: "Lamborghini Veneno",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "pagani-zonda-revolucion",
    name: "Pagani Zonda Revolucion",
    price: 2_800_000,
    tier: "Ultra-Rare",
    image: wikiFile("Pagani_Zonda_Revolución_(cropped).jpg"),
    wikiTitle: "Pagani_Zonda",
    hp: 789, topSpeed: 220, origin: "Italy 🇮🇹",
    googleQuery: "Pagani Zonda Revolucion",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "rolls-royce-sweptail",
    name: "Rolls-Royce Sweptail",
    price: 13_000_000,
    tier: "Ultra-Rare",
    image: wikiFile("Rolls-Royce_Sweptail_(cropped).jpg"),
    wikiTitle: "Rolls-Royce_Sweptail",
    hp: 453, topSpeed: 155, origin: "UK 🇬🇧",
    googleQuery: "Rolls-Royce Sweptail one-off",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "bugatti-la-voiture-noire",
    name: "Bugatti La Voiture Noire",
    price: 18_700_000,
    tier: "Ultra-Rare",
    image: wikiFile("Bugatti_La_Voiture_Noire_(cropped).jpg"),
    wikiTitle: "Bugatti_Type_57",
    hp: 1479, topSpeed: 261, origin: "France 🇫🇷",
    googleQuery: "Bugatti La Voiture Noire",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "pagani-imola",
    name: "Pagani Imola",
    price: 5_400_000,
    tier: "Ultra-Rare",
    image: wikiFile("Pagani_Imola_(2020)_(cropped).jpg"),
    wikiTitle: "Pagani_Huayra",
    hp: 827, topSpeed: 234, origin: "Italy 🇮🇹",
    googleQuery: "Pagani Imola track hypercar",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "ferrari-250-gto",
    name: "Ferrari 250 GTO",
    price: 48_000_000,
    tier: "Ultra-Rare",
    image: wikiFile("Ferrari_250_GTO_1962_2.jpg"),
    wikiTitle: "Ferrari_250_GTO",
    hp: 300, topSpeed: 174, origin: "Italy 🇮🇹",
    googleQuery: "Ferrari 250 GTO 1962",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "lamborghini-sian",
    name: "Lamborghini Sián FKP 37",
    price: 3_600_000,
    tier: "Ultra-Rare",
    image: wikiFile("Lamborghini_Sian_FKP_37_(cropped).jpg"),
    wikiTitle: "Lamborghini_Sián_FKP_37",
    hp: 819, topSpeed: 217, origin: "Italy 🇮🇹",
    googleQuery: "Lamborghini Sian FKP 37 hybrid",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "koenigsegg-ccxr-trevita",
    name: "Koenigsegg CCXR Trevita",
    price: 4_800_000,
    tier: "Ultra-Rare",
    image: wikiFile("Koenigsegg_CCXR_Trevita_(2009)_(cropped).jpg"),
    wikiTitle: "Koenigsegg_CCX",
    hp: 1004, topSpeed: 254, origin: "Sweden 🇸🇪",
    googleQuery: "Koenigsegg CCXR Trevita diamond weave",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "bugatti-mistral",
    name: "Bugatti Mistral",
    price: 5_000_000,
    tier: "Ultra-Rare",
    image: wikiFile("Bugatti_Mistral_(2022)_(cropped).jpg"),
    wikiTitle: "Bugatti_Mistral",
    hp: 1577, topSpeed: 261, origin: "France 🇫🇷",
    googleQuery: "Bugatti Mistral roadster 2022",
    color: TIER_COLOR["Ultra-Rare"],
  },
  {
    id: "mercedes-clk-gtr",
    name: "Mercedes-Benz CLK GTR",
    price: 4_000_000,
    tier: "Ultra-Rare",
    image: wikiFile("Mercedes-Benz_CLK_GTR_(1997)_(cropped).jpg"),
    wikiTitle: "Mercedes-Benz_CLK_GTR",
    hp: 612, topSpeed: 198, origin: "Germany 🇩🇪",
    googleQuery: "Mercedes Benz CLK GTR AMG 1998",
    color: TIER_COLOR["Ultra-Rare"],
  },
];

export function getCarById(id: string): Car | undefined {
  return CARS.find(c => c.id === id);
}

export function findCarByName(query: string): Car | undefined {
  const q = query.toLowerCase().trim();
  return (
    CARS.find(c => c.id === q) ??
    CARS.find(c => c.name.toLowerCase() === q) ??
    CARS.find(c => c.name.toLowerCase().includes(q)) ??
    CARS.find(c => c.id.includes(q.replace(/\s+/g, "-")))
  );
}

export function getCarsByTier(tier: CarTier): Car[] {
  return CARS.filter(c => c.tier === tier);
}

export const ALL_TIERS: CarTier[] = ["Budget", "Mid-Range", "Exotic", "Hypercar", "Ultra-Rare"];
